### PR TITLE
Added EpicEditor

### PR DESCRIPTION
**Pull request by OscarGodson**
Added EpicEditor link. I'm not sure how many stars you need (is over 2.5k enough?) or what the criteria is, but throwing this in here.

### CODE REVIEW

**Comment by stevestreza** [comment]
This doesn't look like a developer portal, is it? The goal isn't to point to projects, but API sites.

**Comment by OscarGodson** [comment]
Its the API for EpicEditor. Just so I know what to contribute in the future, what's the difference between an API doc site for a JS project and say Pocket? Are you just looking for REST APIs?

**Comment by stevestreza** [comment]
I guess I'm just not sure if this falls under the scope of the project. The intention was to have consistent, easy URL-based access to frequently visited developer sites, which usually translates to sites for REST APIs and OAuth keys and stuff like that. That said, I could see use for having URLs for projects like this (and Rails/Django/Express.js/etc). Might be worth separating out code projects from developer portals. Will think about this.

**Comment by stevestreza** [comment]
Ok, so officially I'll allow frameworks/components. One day I may sort/show them differently from services.

**Pull request merged**
