### PR TITLE
Add Marvel Developer Portal

### PR DESCRIPTION
**Pull request by danimal**

### CODE REVIEW

**Comment by nquinlan** [comment]
Thanks for the PR, sorry it took a bit.

**Comment by danimal** [comment]
Don’t ever apologize Nick, you have a job and a life too. ;)

Dan

**Comment by pixelyunicorn** [comment]
Marvel's API is just plain brilliant. Thanks for adding it!

**Comment by danimal** [comment]
@LabLayers :thumbsup:

**Pull request merged**
