### PR TITLE
Create NPR.json

### PR DESCRIPTION
**Pull request by baileyspace**

### CODE REVIEW

**Comment by nquinlan** [comment]
Thanks for the PR! :confetti_ball:

It was great to meet you yesterday!

**Comment by baileyspace** [comment]
Pleasure was all mine :) Also, I just realized we need to add the Pop Up Archive API. Duh! Thanks for the loon.

**Comment by nquinlan** [comment]
Fo'shosies! Thanks for chatting!

How'd you like the loon NPR piece?

**Comment by baileyspace** [comment]
Beautiful. Officially my favorite bird call. Although, I confess, the
bowerbird remains my favorite bird.
ᐧ

Pop Up Archive
popuparchive.com

2014-07-09 10:25 GMT-07:00 Nick Quinlan notifications@github.com:

**Comment by nquinlan** [comment]
Oh man, Bowerbirds are an awesome second to loons in my opinion.

**Pull request merged**
